#!/usr/bin/env node

/**
 * Database Type Generation Pipeline
 * Generates TypeScript types from database schemas for all supported providers
 */

import { execSync } from 'child_process';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

interface TypeGenConfig {
  provider: 'supabase' | 'neon' | 'postgres';
  projectId?: string;
  dbUrl?: string;
  schema?: string;
  outputPath: string;
}

class DatabaseTypeGenerator {
  private configs: Map<string, TypeGenConfig> = new Map();

  constructor() {
    this.setupConfigs();
  }

  private setupConfigs(): void {
    // Supabase configuration
    const supabaseProjectId = process.env.SUPABASE_PROJECT_ID;
    if (supabaseProjectId) {
      this.configs.set('supabase', {
        provider: 'supabase',
        projectId: supabaseProjectId,
        schema: 'public',
        outputPath: join(__dirname, '../src/types/generated/supabase.ts'),
      });
    }

    // Neon configuration
    const neonUrl = process.env.NEON_URL;
    if (neonUrl) {
      this.configs.set('neon', {
        provider: 'neon',
        dbUrl: neonUrl,
        schema: 'public',
        outputPath: join(__dirname, '../src/types/generated/neon.ts'),
      });
    }

    // Postgres configuration
    const postgresUrl = process.env.DATABASE_URL;
    if (postgresUrl) {
      this.configs.set('postgres', {
        provider: 'postgres',
        dbUrl: postgresUrl,
        schema: 'public',
        outputPath: join(__dirname, '../src/types/generated/postgres.ts'),
      });
    }
  }

  /**
   * Generate types for all configured providers
   */
  async generateAll(): Promise<void> {
    console.log('🚀 Starting database type generation...\n');

    for (const [name, config] of this.configs) {
      try {
        await this.generateForProvider(name, config);
        console.log(`✅ ${name}: Types generated successfully`);
      } catch (error) {
        console.error(`❌ ${name}: Failed to generate types - ${error.message}`);
      }
    }

    console.log('\n🎉 Type generation completed!');
  }

  /**
   * Generate types for a specific provider
   */
  private async generateForProvider(name: string, config: TypeGenConfig): Promise<void> {
    console.log(`📝 Generating types for ${name}...`);

    // Ensure output directory exists
    const outputDir = join(config.outputPath, '..');
    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
    }

    switch (config.provider) {
      case 'supabase':
        await this.generateSupabaseTypes(config);
        break;
      case 'neon':
        await this.generatePostgresTypes(config);
        break;
      case 'postgres':
        await this.generatePostgresTypes(config);
        break;
      default:
        throw new Error(`Unsupported provider: ${config.provider}`);
    }
  }

  /**
   * Generate Supabase types using Supabase CLI
   */
  private async generateSupabaseTypes(config: TypeGenConfig): Promise<void> {
    try {
      // Check if Supabase CLI is installed
      execSync('npx supabase --version', { stdio: 'pipe' });
    } catch (error) {
      throw new Error('Supabase CLI not found. Install with: npm i supabase@">=1.8.1" --save-dev');
    }

    const command = config.projectId
      ? `npx supabase gen types typescript --project-id "${config.projectId}" --schema ${config.schema}`
      : `npx supabase gen types typescript --local --schema ${config.schema}`;

    const types = execSync(command, {
      encoding: 'utf8',
      stdio: 'pipe',
    });

    // Add custom header and exports
    const header = `/**
 * Auto-generated Supabase database types
 * Generated on: ${new Date().toISOString()}
 * Provider: Supabase
 * Schema: ${config.schema}
 * 
 * ⚠️ DO NOT EDIT MANUALLY - This file is generated by the type generation pipeline
 * Run 'pnpm db:generate' to regenerate these types
 */

`;

    const enhancedTypes = header + this.addCustomTypes(types.toString(), 'supabase');
    writeFileSync(config.outputPath, enhancedTypes);
  }

  /**
   * Generate PostgreSQL types using schema introspection
   */
  private async generatePostgresTypes(config: TypeGenConfig): Promise<void> {
    if (!config.dbUrl) {
      throw new Error('Database URL required for PostgreSQL type generation');
    }

    // For now, create a basic interface structure
    // In a real implementation, you'd use a library like 'pg' to introspect the schema
    const basicTypes = `/**
 * Auto-generated PostgreSQL database types
 * Generated on: ${new Date().toISOString()}
 * Provider: ${config.provider}
 * Schema: ${config.schema}
 * 
 * ⚠️ DO NOT EDIT MANUALLY - This file is generated by the type generation pipeline
 * Run 'pnpm db:generate' to regenerate these types
 */

// Basic PostgreSQL types - replace with actual schema introspection
export interface Database {
  [key: string]: any;
}

export interface Tables {
  [key: string]: {
    Row: any;
    Insert: any;
    Update: any;
  };
}

export interface Enums {
  [key: string]: any;
}

export interface CompositeTypes {
  [key: string]: any;
}

export interface Functions {
  [key: string]: any;
}

export interface Views {
  [key: string]: {
    Row: any;
  };
}
`;

    const enhancedTypes = this.addCustomTypes(basicTypes, config.provider);
    writeFileSync(config.outputPath, enhancedTypes);
  }

  /**
   * Add custom types and utilities to generated types
   */
  private addCustomTypes(types: string, provider: string): string {
    const customTypes = `

// ===========================================
// CUSTOM TYPES AND UTILITIES
// ===========================================

/**
 * Generic database row with base entity fields
 */
export interface DatabaseEntity {
  id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Common query options
 */
export interface QueryOptions {
  limit?: number;
  offset?: number;
  orderBy?: string;
  orderDirection?: 'asc' | 'desc';
}

/**
 * Pagination response
 */
export interface PaginatedResponse<T> {
  data: T[];
  count: number;
  hasMore: boolean;
}

/**
 * Database error types
 */
export interface DatabaseError {
  code: string;
  message: string;
  details?: any;
  hint?: string;
}

// ===========================================
// PROVIDER-SPECIFIC UTILITIES
// ===========================================

${this.getProviderUtilities(provider)}
`;

    return types + customTypes;
  }

  /**
   * Get provider-specific utilities
   */
  private getProviderUtilities(provider: string): string {
    switch (provider) {
      case 'supabase':
        return `
/**
 * Supabase-specific utilities
 */
export type SupabaseClient = import('@supabase/supabase-js').SupabaseClient<Database>;

/**
 * Create a typed Supabase client
 */
export function createSupabaseClient(url: string, key: string): SupabaseClient {
  return new (require('@supabase/supabase-js').createClient)<Database>(url, key);
}

/**
 * Type-safe table reference
 */
export type Table<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T];

/**
 * Type-safe row type
 */
export type Row<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];

/**
 * Type-safe insert type
 */
export type Insert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];

/**
 * Type-safe update type
 */
export type Update<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
`;

      case 'neon':
      case 'postgres':
        return `
/**
 * PostgreSQL-specific utilities
 */
export interface PostgresPool {
  query: (text: string, params?: any[]) => Promise<any>;
  end: () => Promise<void>;
}

/**
 * Connection factory
 */
export function createPostgresPool(connectionString: string): PostgresPool {
  // Implementation would use 'pg' library
  throw new Error('PostgreSQL pool implementation required');
}

/**
 * SQL template literal tag for type-safe queries
 */
export function sql<T = any>(strings: TemplateStringsArray, ...values: any[]): {
  text: string;
  values: any[];
  type: 'PostgresQuery';
} {
  return {
    text: strings.join('?'),
    values,
    type: 'PostgresQuery'
  };
}
`;

      default:
        return '';
    }
  }

  /**
   * Generate index file for all types.
   * Always creates the generated directory first so the file can be written
   * even when no database env vars are configured.
   */
  generateIndex(): void {
    const indexPath = join(__dirname, '../src/types/generated/index.ts');
    const outputDir = join(indexPath, '..');

    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
    }

    let indexContent = `/**
 * Generated database types index
 * Generated on: ${new Date().toISOString()}
 *
 * ⚠️ DO NOT EDIT MANUALLY - This file is generated by the type generation pipeline.
 * Run 'pnpm db:generate' (with appropriate env vars) to regenerate these types.
 */

`;

    if (this.configs.size === 0) {
      indexContent += `// No database providers were configured during generation.
// Set SUPABASE_PROJECT_ID, NEON_URL, or DATABASE_URL and re-run 'pnpm db:generate'.

`;
    } else {
      for (const [name] of this.configs) {
        indexContent += `export * from './${name}';\n`;
      }
      indexContent += '\n';
    }

    // Common utilities always present
    indexContent += `// Common utilities across all providers
export type DatabaseProvider = 'supabase' | 'neon' | 'postgres';
`;

    writeFileSync(indexPath, indexContent);
  }
}

// CLI execution
if (require.main === module) {
  const generator = new DatabaseTypeGenerator();

  generator
    .generateAll()
    .then(() => {
      generator.generateIndex();
      process.exit(0);
    })
    .catch((error) => {
      console.error('Type generation failed:', error);
      process.exit(1);
    });
}

export { DatabaseTypeGenerator };
